variable "project" {
  type        = string
  default     = "sales-agent"
  description = "Project tag prefix"
}

variable "region" {
  type        = string
  default     = "us-east-1"
  description = "AWS region (Bedrock anthropic models live in us-east-1, us-west-2)"
}

variable "instance_type" {
  type        = string
  default     = "t3.micro"
  description = "EC2 instance type (t3.micro is free tier for 12mo)"
}

variable "db_instance_type" {
  type        = string
  default     = "db.t3.micro"
  description = "RDS instance class (db.t3.micro is free tier for 12mo)"
}

variable "db_username" {
  type    = string
  default = "agent"
}

# DB password is generated by random_password (see ssm.tf) — do NOT put it here.

variable "ssh_cidr" {
  type        = string
  default     = "0.0.0.0/0"
  description = "CIDR allowed to SSH to the EC2 box. CHANGE THIS to your IP/32."
}

variable "public_key_path" {
  type        = string
  default     = "~/.ssh/id_ed25519.pub"
  description = "Path to your public SSH key"
}

variable "anthropic_api_key" {
  type        = string
  default     = ""
  description = "Anthropic API key (used when companies have cloud_provider=anthropic). Stored in SSM."
  sensitive   = true
}

variable "bootstrap_admin_email" {
  type    = string
  default = "boss@local.dev"
}

variable "bootstrap_admin_password" {
  type      = string
  default   = "change-this-immediately"
  sensitive = true
}

variable "frontend_bucket_suffix" {
  type        = string
  default     = ""
  description = "Optional suffix for S3 bucket (must be globally unique). Defaults to random."
}

variable "tailscale_auth_key" {
  type        = string
  default     = ""
  description = "Optional Tailscale auth key. If set, EC2 joins your tailnet so you can route Ollama traffic home."
  sensitive   = true
}
